export const ERROR_CODES = {
	TASK_NOT_FOUND: 'TASK_NOT_FOUND',
	TASKS_NOT_FOUND: 'TASKS_NOT_FOUND',
	USERS_NOT_FOUND: 'USERS_NOT_FOUND',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
	INCORRECT_DATA: 'INCORRECT_DATA',
}
